---
title: "05-quantile-errors"
output: html_document
---

## Data Science 5620 --- Deliverable 05
### Quantile Error
### Rastko Stojsin


```{r}
library(ggplot2)
library(tidyverse)
```


```{r}
sample_grid <- expand.grid(
    N = (1:5000)
  , samples = NA_real_
  )
sample_grid[2] <- rnorm(5000,0,1)
```

```{r}
rand_sample_grid <- expand.grid(
     N = (1:5000)
  , "0.025" = NA_integer_
  , "0.05" = NA_integer_
  , "0.10" = NA_integer_
  , "0.15" = NA_integer_
  , "0.2"  = NA_integer_
  , "0.25" = NA_real_
  , "0.3" = NA_integer_
  , "0.35" = NA_integer_
  , "0.4" = NA_integer_
  , "0.45" = NA_integer_
  , "0.5" = NA_real_
  , third_quart = NA_real_
  , "0.975" = NA_real_
  , max = NA_real_ 
  , length = NA_real_
  , length_percentile = NA_real_
)
```

```{r}
calc_summary <- function(p,data) {
  rand_sample_grid <- matrix(NA, ncol=length(p), nrow=5000)
  
  for(i in 1:5000){
    resamp.data <- rnorm(200)
    rand_sample_grid[i,] <- quantile(resamp.data,p)
  }
  # set.seed(i)
  # df <- randomRows(sample_grid,200)
  # min <- quantile(df$samples, 0.00)
  # fp <- quantile(df$samples, 0.025)
  # first_quart <- quantile(df$samples, 0.25)
  # med <- quantile(df$samples, 0.5)
  # third_quart <- quantile(df$samples, 0.75)
  # lp <- quantile(df$samples, 0.975)
  # max <- quantile(df$samples, 1)
  # c(min, fp, first_quart, med, third_quart, lp, max)
  return(rand_sample_grid)
}

rand_sample_grid <- calc_summary(p=seq(0.05,0.95,by=0.05), data=sample_grid)
```

```{r}
randomRows = function(df,n){
   return(df[sample(nrow(df),n),])
}
```

```{r}
for(i in 1:nrow(rand_sample_grid)){
  rand_sample_grid[i,c("min","0.025", "first_quart", "med", "third_quart", "0.975", "max")] <- calc_summary(i)
}
rand_sample_grid <- rand_sample_grid %>% 
  mutate("length" = rand_sample_grid$`0.975` - rand_sample_grid$`0.025`) 
```


```{r}
ggplot(rand_sample_grid, aes(length)) +
  geom_histogram(binwidth = 0.03)
```


```{r}

```

